server:
  port: 8080

jasypt:
  encryptor:
    password: fhyPayaso

spring:
  datasource:
    # 基本数据库配置
    name: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/orochi
    username: root
    password: ENC(2Oo6WXGMZV/WdP7ZrDOvlkN08wMfU7Ee)

    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 1
      # 最小下限
      min-idle: 1
      # 最大上限
      max-active: 20
      # 获取连接等待超时时间(ms)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接(ms)
      time-between-eviction-runs-millis: 60000
      # 错误重试次数
      connection-error-retry-attempts: 2
      # 最小生存时间(ms)
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙（防止SQL注入）
      filters: stat,wall
      validation-query: select 1


  redis:
    database: 0
    timeout: 5000ms
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间
        max-wait:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0


mybatis:
  # mapper路径
  mapper-locations: classpath:mappers/*.xml
  # 实体类包路径
  type-aliases-package: com.fhypayaso.orochi.bean
  configuration:
    cache-enabled: false
    # 使用jdbc获取数据库自增id
    use-generated-keys: true
    # 列别名替换别名
    use-column-label: true
    # 驼峰命名
    map-underscore-to-camel-case: true
    # 不忽略空字段
    call-setters-on-nulls: true
